# Generated by Django 2.0.6 on 2018-06-10 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mining',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 10, 15, 11, 52, 508837), verbose_name='添加时间'),
        ),
    ]
