# Generated by Django 2.0.6 on 2018-06-10 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0007_auto_20180610_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mining',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 10, 21, 22, 49, 807875), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='mining',
            name='extract',
            field=models.FloatField(default=0, verbose_name='已经被取到钱包的矿石'),
        ),
        migrations.AlterField(
            model_name='mining',
            name='force',
            field=models.IntegerField(default=100, verbose_name='矿机算力'),
        ),
    ]
