# Generated by Django 2.0.6 on 2018-06-10 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0008_auto_20180610_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mining',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 10, 21, 26, 26, 241613), verbose_name='添加时间'),
        ),
    ]
