# Generated by Django 2.0.6 on 2018-06-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0011_auto_20180610_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='mining',
            name='sign_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='用户签到的时间'),
        ),
    ]
